### ISSUE TITLE
How to run this project? Please post the execution steps.

### ISSUE THREAD

**Issue by chaiein** [tkelestemur/ackermann_robot#1]

**Comment by tkelestemur** [comment]
@chaiein you need to have ROS installed in your system. After that you need to build it in your ROS workspace and launch it from command line. You can find further information on http://wiki.ros.org/

**Comment by chaiein** [comment]
chaiein@ubuntu:~/ackermann_robot-master/build$ make
[100%] Building CXX object CMakeFiles/simulation.dir/src/simulation.cpp.o
/home/vrlab/ackermann_robot-master/src/simulation.cpp:8:34: fatal error: vrep_common/VrepInfo.h: No such file or directory
 #include "vrep_common/VrepInfo.h"

**Comment by tkelestemur** [comment]
standart make won't work here. you need install ROS and use catkin_make provided from ROS. You can find everything on ROS wiki.
